/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OauthLayoutRouteImport } from './routes/_oauthLayout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents.index'
import { Route as AuthenticatedAgentsNewRouteImport } from './routes/_authenticated/agents.new'
import { Route as AuthenticatedAgentsIdRouteImport } from './routes/_authenticated/agents.$id'
import { Route as AuthenticatedAgentsIdIndexRouteImport } from './routes/_authenticated/agents.$id.index'
import { Route as OauthLayoutPersonalAgentsAuthSuccessRouteImport } from './routes/_oauthLayout.personal-agents.auth.success'
import { Route as OauthLayoutPersonalAgentsAuthErrorRouteImport } from './routes/_oauthLayout.personal-agents.auth.error'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLayoutRoute = OauthLayoutRouteImport.update({
  id: '/_oauthLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsNewRoute = AuthenticatedAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIdRoute = AuthenticatedAgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsIdIndexRoute =
  AuthenticatedAgentsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgentsIdRoute,
  } as any)
const OauthLayoutPersonalAgentsAuthSuccessRoute =
  OauthLayoutPersonalAgentsAuthSuccessRouteImport.update({
    id: '/personal-agents/auth/success',
    path: '/personal-agents/auth/success',
    getParentRoute: () => OauthLayoutRoute,
  } as any)
const OauthLayoutPersonalAgentsAuthErrorRoute =
  OauthLayoutPersonalAgentsAuthErrorRouteImport.update({
    id: '/personal-agents/auth/error',
    path: '/personal-agents/auth/error',
    getParentRoute: () => OauthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/personal-agents/auth/error': typeof OauthLayoutPersonalAgentsAuthErrorRoute
  '/personal-agents/auth/success': typeof OauthLayoutPersonalAgentsAuthSuccessRoute
  '/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/agents/new': typeof AuthenticatedAgentsNewRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/personal-agents/auth/error': typeof OauthLayoutPersonalAgentsAuthErrorRoute
  '/personal-agents/auth/success': typeof OauthLayoutPersonalAgentsAuthSuccessRoute
  '/agents/$id': typeof AuthenticatedAgentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_oauthLayout': typeof OauthLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/agents/$id': typeof AuthenticatedAgentsIdRouteWithChildren
  '/_authenticated/agents/new': typeof AuthenticatedAgentsNewRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_oauthLayout/personal-agents/auth/error': typeof OauthLayoutPersonalAgentsAuthErrorRoute
  '/_oauthLayout/personal-agents/auth/success': typeof OauthLayoutPersonalAgentsAuthSuccessRoute
  '/_authenticated/agents/$id/': typeof AuthenticatedAgentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/settings'
    | '/agents/$id'
    | '/agents/new'
    | '/agents'
    | '/personal-agents/auth/error'
    | '/personal-agents/auth/success'
    | '/agents/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/settings'
    | '/agents/new'
    | '/agents'
    | '/personal-agents/auth/error'
    | '/personal-agents/auth/success'
    | '/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_oauthLayout'
    | '/about'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/agents/$id'
    | '/_authenticated/agents/new'
    | '/_authenticated/agents/'
    | '/_oauthLayout/personal-agents/auth/error'
    | '/_oauthLayout/personal-agents/auth/success'
    | '/_authenticated/agents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OauthLayoutRoute: typeof OauthLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_oauthLayout': {
      id: '/_oauthLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/new': {
      id: '/_authenticated/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedAgentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/$id': {
      id: '/_authenticated/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AuthenticatedAgentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/$id/': {
      id: '/_authenticated/agents/$id/'
      path: '/'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AuthenticatedAgentsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAgentsIdRoute
    }
    '/_oauthLayout/personal-agents/auth/success': {
      id: '/_oauthLayout/personal-agents/auth/success'
      path: '/personal-agents/auth/success'
      fullPath: '/personal-agents/auth/success'
      preLoaderRoute: typeof OauthLayoutPersonalAgentsAuthSuccessRouteImport
      parentRoute: typeof OauthLayoutRoute
    }
    '/_oauthLayout/personal-agents/auth/error': {
      id: '/_oauthLayout/personal-agents/auth/error'
      path: '/personal-agents/auth/error'
      fullPath: '/personal-agents/auth/error'
      preLoaderRoute: typeof OauthLayoutPersonalAgentsAuthErrorRouteImport
      parentRoute: typeof OauthLayoutRoute
    }
  }
}

interface AuthenticatedAgentsIdRouteChildren {
  AuthenticatedAgentsIdIndexRoute: typeof AuthenticatedAgentsIdIndexRoute
}

const AuthenticatedAgentsIdRouteChildren: AuthenticatedAgentsIdRouteChildren = {
  AuthenticatedAgentsIdIndexRoute: AuthenticatedAgentsIdIndexRoute,
}

const AuthenticatedAgentsIdRouteWithChildren =
  AuthenticatedAgentsIdRoute._addFileChildren(
    AuthenticatedAgentsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAgentsIdRoute: typeof AuthenticatedAgentsIdRouteWithChildren
  AuthenticatedAgentsNewRoute: typeof AuthenticatedAgentsNewRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAgentsIdRoute: AuthenticatedAgentsIdRouteWithChildren,
  AuthenticatedAgentsNewRoute: AuthenticatedAgentsNewRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OauthLayoutRouteChildren {
  OauthLayoutPersonalAgentsAuthErrorRoute: typeof OauthLayoutPersonalAgentsAuthErrorRoute
  OauthLayoutPersonalAgentsAuthSuccessRoute: typeof OauthLayoutPersonalAgentsAuthSuccessRoute
}

const OauthLayoutRouteChildren: OauthLayoutRouteChildren = {
  OauthLayoutPersonalAgentsAuthErrorRoute:
    OauthLayoutPersonalAgentsAuthErrorRoute,
  OauthLayoutPersonalAgentsAuthSuccessRoute:
    OauthLayoutPersonalAgentsAuthSuccessRoute,
}

const OauthLayoutRouteWithChildren = OauthLayoutRoute._addFileChildren(
  OauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OauthLayoutRoute: OauthLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
